// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: api/foobar/v1/foobar.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoobarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo string `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar int32  `protobuf:"varint,2,opt,name=bar,proto3" json:"bar,omitempty"`
}

func (x *FoobarRequest) Reset() {
	*x = FoobarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foobar_v1_foobar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoobarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoobarRequest) ProtoMessage() {}

func (x *FoobarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foobar_v1_foobar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoobarRequest.ProtoReflect.Descriptor instead.
func (*FoobarRequest) Descriptor() ([]byte, []int) {
	return file_api_foobar_v1_foobar_proto_rawDescGZIP(), []int{0}
}

func (x *FoobarRequest) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

func (x *FoobarRequest) GetBar() int32 {
	if x != nil {
		return x.Bar
	}
	return 0
}

type FoobarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FoobarReply) Reset() {
	*x = FoobarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_foobar_v1_foobar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoobarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoobarReply) ProtoMessage() {}

func (x *FoobarReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_foobar_v1_foobar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoobarReply.ProtoReflect.Descriptor instead.
func (*FoobarReply) Descriptor() ([]byte, []int) {
	return file_api_foobar_v1_foobar_proto_rawDescGZIP(), []int{1}
}

func (x *FoobarReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_foobar_v1_foobar_proto protoreflect.FileDescriptor

var file_api_foobar_v1_foobar_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x0d,
	0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x66, 0x6f, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x6f, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x62, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x62, 0x61,
	0x72, 0x22, 0x1d, 0x0a, 0x0b, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x32, 0x39, 0x0a, 0x06, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x12, 0x2f, 0x0a, 0x0d, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x12, 0x0e, 0x2e, 0x46, 0x6f,
	0x6f, 0x62, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x46, 0x6f,
	0x6f, 0x62, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x57,
	0x65, 0x65, 0x6b, 0x30, 0x34, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_foobar_v1_foobar_proto_rawDescOnce sync.Once
	file_api_foobar_v1_foobar_proto_rawDescData = file_api_foobar_v1_foobar_proto_rawDesc
)

func file_api_foobar_v1_foobar_proto_rawDescGZIP() []byte {
	file_api_foobar_v1_foobar_proto_rawDescOnce.Do(func() {
		file_api_foobar_v1_foobar_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_foobar_v1_foobar_proto_rawDescData)
	})
	return file_api_foobar_v1_foobar_proto_rawDescData
}

var file_api_foobar_v1_foobar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_foobar_v1_foobar_proto_goTypes = []interface{}{
	(*FoobarRequest)(nil), // 0: FoobarRequest
	(*FoobarReply)(nil),   // 1: FoobarReply
}
var file_api_foobar_v1_foobar_proto_depIdxs = []int32{
	0, // 0: Foobar.RegisteFoobar:input_type -> FoobarRequest
	1, // 1: Foobar.RegisteFoobar:output_type -> FoobarReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_foobar_v1_foobar_proto_init() }
func file_api_foobar_v1_foobar_proto_init() {
	if File_api_foobar_v1_foobar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_foobar_v1_foobar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoobarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_foobar_v1_foobar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoobarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_foobar_v1_foobar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_foobar_v1_foobar_proto_goTypes,
		DependencyIndexes: file_api_foobar_v1_foobar_proto_depIdxs,
		MessageInfos:      file_api_foobar_v1_foobar_proto_msgTypes,
	}.Build()
	File_api_foobar_v1_foobar_proto = out.File
	file_api_foobar_v1_foobar_proto_rawDesc = nil
	file_api_foobar_v1_foobar_proto_goTypes = nil
	file_api_foobar_v1_foobar_proto_depIdxs = nil
}
