// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// FoobarClient is the client API for Foobar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoobarClient interface {
	RegisteFoobar(ctx context.Context, in *FoobarRequest, opts ...grpc.CallOption) (*FoobarReply, error)
}

type foobarClient struct {
	cc grpc.ClientConnInterface
}

func NewFoobarClient(cc grpc.ClientConnInterface) FoobarClient {
	return &foobarClient{cc}
}

func (c *foobarClient) RegisteFoobar(ctx context.Context, in *FoobarRequest, opts ...grpc.CallOption) (*FoobarReply, error) {
	out := new(FoobarReply)
	err := c.cc.Invoke(ctx, "/Foobar/RegisteFoobar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoobarServer is the server API for Foobar service.
// All implementations must embed UnimplementedFoobarServer
// for forward compatibility
type FoobarServer interface {
	RegisteFoobar(context.Context, *FoobarRequest) (*FoobarReply, error)
	mustEmbedUnimplementedFoobarServer()
}

// UnimplementedFoobarServer must be embedded to have forward compatible implementations.
type UnimplementedFoobarServer struct {
}

func (UnimplementedFoobarServer) RegisteFoobar(context.Context, *FoobarRequest) (*FoobarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteFoobar not implemented")
}
func (UnimplementedFoobarServer) mustEmbedUnimplementedFoobarServer() {}

// UnsafeFoobarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoobarServer will
// result in compilation errors.
type UnsafeFoobarServer interface {
	mustEmbedUnimplementedFoobarServer()
}

func RegisterFoobarServer(s grpc.ServiceRegistrar, srv FoobarServer) {
	s.RegisterService(&Foobar_ServiceDesc, srv)
}

func _Foobar_RegisteFoobar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoobarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoobarServer).RegisteFoobar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Foobar/RegisteFoobar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoobarServer).RegisteFoobar(ctx, req.(*FoobarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Foobar_ServiceDesc is the grpc.ServiceDesc for Foobar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Foobar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Foobar",
	HandlerType: (*FoobarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisteFoobar",
			Handler:    _Foobar_RegisteFoobar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/foobar/v1/foobar.proto",
}
