// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/hi20160616/Go-000/Week04/homework/internal/biz"
	"github.com/hi20160616/Go-000/Week04/homework/internal/data"
)

// Injectors from wire.go:

func InitFoobarCase() *biz.FoobarCase {
	foobarRepo := data.NewFoobarRepo()
	foobarCase := biz.NewFoobarCase(foobarRepo)
	return foobarCase
}
